spring.application.name=EasyOrder

# Direct Aiven MySQL Connection Test
spring.datasource.url=jdbc:mysql://://aivencloud.com
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_v3Gvj4655l3SlCKu32M

# Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

server.port=8080
cors.allowed-origins=http://localhost:3000
